/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionbiblio;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.JSpinner;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Mbolatiana
 */
public class FenAjoutLivre extends javax.swing.JFrame {

    /**
     * Creates new form FenAjoutLivre
     */
    private static biblio bi;
     private static PanelLivre panelLivre; // Ajout de la référence au PanelLivre
     private static String lastId;
     private int nouveauId;
     
    public FenAjoutLivre(biblio bi,PanelLivre panelLivre,String lastId) {
        initComponents();
        this.bi = bi;
        this.panelLivre = panelLivre;
        this.lastId = lastId;   
        //********************************************************************
        
        //mis en place du nouveau Id     
        this.lastId = lastId.substring(3);
        nouveauId = Integer.parseInt(this.lastId)+1;
        numLivreAjout.setText("LI0"+(nouveauId));
        //******************************************************************
        
         // Obtenir la date actuelle et la définir comme valeur par défaut dans txtDate
    Date date = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    String formattedDate = dateFormat.format(date);
    txtDate.setText(formattedDate);
    //***************************************************************************
    //regex sur les inputs
          
           DocumentListener doc = new DocumentListener(){
                  @Override
    public void insertUpdate(DocumentEvent e) {
        desactiveBtn(); 
       // Pattern.matches("a-zA-Z",txtnomLecteur.getText());
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
desactiveBtn();     }

    @Override
    public void changedUpdate(DocumentEvent e) {
        // Ne sera pas appelé pour les champs de texte simples
desactiveBtn();    }
               
           };
           
           
            titreAjout.getDocument().addDocumentListener(doc);
            auteurAjouter.getDocument().addDocumentListener(doc);
            //*******************************************************
            
    }
    // fonction pour le regex
public  void desactiveBtn(){
         if ( !titreAjout.getText().isEmpty() && !auteurAjouter.getText().isEmpty() && Pattern.matches("[a-zA-Z]+",titreAjout.getText()) && Pattern.matches("[a-zA-Z]+",auteurAjouter.getText()) ){
             btnAjoutLivre.setEnabled(true);
         }else{
             btnAjoutLivre.setEnabled(false);
         }

    }
//***************************************************
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jLabel1 = new javax.swing.JLabel();
        titreAjout = new javax.swing.JTextField();
        btnAjoutLivre = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        auteurAjouter = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numLivreAjout = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        btnDate = new javax.swing.JButton();

        dateChooser1.setTextField(txtDate);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Ajout de livre");

        btnAjoutLivre.setText("Ajouter cet livre");
        btnAjoutLivre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjoutLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutLivreActionPerformed(evt);
            }
        });

        jLabel2.setText("Titre");

        jLabel3.setText("Auteur");

        jLabel4.setText("Date d'édition");

        jLabel5.setText("NumLivre");

        numLivreAjout.setEditable(false);

        btnDate.setText("...");
        btnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numLivreAjout, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(titreAjout, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(auteurAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(txtDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAjoutLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numLivreAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titreAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(auteurAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDate))
                .addGap(33, 33, 33)
                .addComponent(btnAjoutLivre)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutLivreActionPerformed
        // TODO add your handling code here:
          Connection con1;
        PreparedStatement insert;
        

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            con1 = DriverManager.getConnection("jdbc:mysql://localhost/baseprojet","root","");
            String sql="Insert into livre(numLivre,Titre,Auteur,date_edition,Disponible,NbFoisPret,remarque) values (?,?,?,?,'OUI','0','')";
            insert = con1.prepareStatement(sql);
            insert.setString(1, numLivreAjout.getText());
            insert.setString(2, titreAjout.getText());
            insert.setString(3, auteurAjouter.getText());
            insert.setString(4, txtDate.getText());
            insert.executeUpdate()  ;
            this.setAlwaysOnTop(false);
            JOptionPane.showMessageDialog(null, "Ajout de livre réussi");
            this.setAlwaysOnTop(true);
            con1.close();
            numLivreAjout.setText("LI0"+(nouveauId = nouveauId + 1));
            titreAjout.setText("");
            auteurAjouter.setText("");
            
            // Actualiser la table dans le PanelLivre
            panelLivre.updateDB1();
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }   
    }//GEN-LAST:event_btnAjoutLivreActionPerformed

    private void btnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateActionPerformed
        // TODO add your handling code here:
//        Calendar calendar = Calendar.getInstance();
//    int year = calendar.get(Calendar.YEAR);
//    int month = calendar.get(Calendar.MONTH);
//    int day = calendar.get(Calendar.DAY_OF_MONTH);
//
//    // Définir la date actuelle dans le DateChooser
//    dateChooser1.setSelectedDate(year, month, day);
        dateChooser1.showPopup();
    }//GEN-LAST:event_btnDateActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        bi.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenAjoutLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenAjoutLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenAjoutLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenAjoutLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenAjoutLivre(bi,panelLivre,lastId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField auteurAjouter;
    private javax.swing.JButton btnAjoutLivre;
    private javax.swing.JButton btnDate;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField numLivreAjout;
    private javax.swing.JTextField titreAjout;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
