/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionbiblio;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author G A S I M I A R O
 */
public class FenRemarqueLivre extends javax.swing.JFrame {

    /**
     * Creates new form FenRemarqueLivre
     */
    private static biblio bi;
   private static PanelLivre panLivre = new PanelLivre(bi);
    
      private static final String usernamme="root";
   private static final String password="";
   private static final String dataConn="jdbc:mysql://localhost/baseprojet";
   
   
   Connection sqlConn=null;
   PreparedStatement pst=null;
    private static Object obj;
    private static String remarque;
    private static String titre;
    
    public FenRemarqueLivre(biblio bi,PanelLivre panLivre,Object o,String titre,String remarque) {
        this.bi = bi;
        this.panLivre= panLivre;
        this.obj=o;
        this.titre = titre;
        this.remarque= remarque;
        
        
        initComponents();
        nomLivre.setText(titre);
        remarqueLivre.setText(remarque);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomLivre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarqueLivre = new javax.swing.JTextArea();
        btnModifRemarque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("REMARQUE DU LIVRE :");

        nomLivre.setEditable(false);
        nomLivre.setBackground(null);
        nomLivre.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nomLivre.setBorder(null);

        remarqueLivre.setColumns(20);
        remarqueLivre.setRows(5);
        jScrollPane1.setViewportView(remarqueLivre);

        btnModifRemarque.setText("MODIFIER");
        btnModifRemarque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModifRemarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifRemarqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(nomLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnModifRemarque, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnModifRemarque, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifRemarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifRemarqueActionPerformed
          try {
              
                  // TODO add your handling code here:
                  Class.forName("com.mysql.cj.jdbc.Driver");
             

            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost/baseprojet","root","");
              pst = sqlConn.prepareStatement(" UPDATE livre set remarque='"+ remarqueLivre.getText()+"' WHERE numLivre='"+obj+"'");
              pst.executeUpdate();
              System.out.println("--"+remarqueLivre.getText()+"--");
              if(remarqueLivre.getText().isEmpty()){
                  System.out.println("avadika OUI");
                  pst = sqlConn.prepareStatement(" UPDATE livre set disponible='OUI' WHERE numLivre='"+obj+"'");
                  pst.executeUpdate();
              }
              else{
                  System.out.println("avadika =non");
                  pst = sqlConn.prepareStatement(" UPDATE livre set disponible='NON' WHERE numLivre='"+obj+"'");
                  pst.executeUpdate();
              }
              this.setAlwaysOnTop(false);
              JOptionPane.showMessageDialog(null, "Modiffication de Remarque avec Succes");
             this.setAlwaysOnTop(true);
              panLivre.updateDB1();
              
          } catch (SQLException ex) {
              Logger.getLogger(FenRemarqueLivre.class.getName()).log(Level.SEVERE, null, ex);
          }
          catch (ClassNotFoundException ex) {
                  Logger.getLogger(FenRemarqueLivre.class.getName()).log(Level.SEVERE, null, ex);
              }
                       
    }//GEN-LAST:event_btnModifRemarqueActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        bi.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenRemarqueLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenRemarqueLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenRemarqueLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenRemarqueLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenRemarqueLivre(bi,panLivre,obj,titre,remarque).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifRemarque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomLivre;
    private javax.swing.JTextArea remarqueLivre;
    // End of variables declaration//GEN-END:variables
}
